In [1]:
from pathlib import Path
import sys

sys.path.append(str(Path.cwd().parent))

In [2]:
from src.transforms import test_transforms
from src.dataset import ImageDataset
import torch

annot_path = Path("../data/preprocessed/trainval/annotations.csv")
img_dir = Path("../data/preprocessed/trainval/images")

# test dataset without transforms
dataset = ImageDataset(annot_path, img_dir)
transformed_dataset = ImageDataset(annot_path, img_dir, test_transforms)

In [3]:
_, truth_labels = next(iter(transformed_dataset))
truth_labels.shape, truth_labels

(torch.Size([5, 5]),
 tensor([[8.0000, 0.5848, 0.7321, 0.1205, 0.3393],
         [8.0000, 0.4196, 0.8482, 0.1741, 0.2902],
         [8.0000, 0.0714, 0.8259, 0.1250, 0.3482],
         [8.0000, 0.5357, 0.6562, 0.1071, 0.2812],
         [8.0000, 0.5893, 0.5402, 0.0714, 0.0893]]))

In [4]:
bboxes = truth_labels[:, -4:]
bboxes.shape, bboxes

(torch.Size([5, 4]),
 tensor([[0.5848, 0.7321, 0.1205, 0.3393],
         [0.4196, 0.8482, 0.1741, 0.2902],
         [0.0714, 0.8259, 0.1250, 0.3482],
         [0.5357, 0.6562, 0.1071, 0.2812],
         [0.5893, 0.5402, 0.0714, 0.0893]]))

In [5]:
truth_labels[:, 0]

tensor([8., 8., 8., 8., 8.])

In [6]:
bbox_preds = torch.randn(100, 21)
bbox_preds

tensor([[-0.8114,  0.3207,  1.2902,  ...,  0.7237, -1.4079,  0.8062],
        [-1.8448, -0.8868,  0.5742,  ...,  1.0284, -1.4961, -1.1337],
        [-0.5967, -0.3511,  0.0821,  ..., -1.1377,  1.5760, -0.2705],
        ...,
        [-0.4972,  0.5631,  0.3575,  ...,  0.2587,  1.0343,  1.1628],
        [ 0.8544,  0.3045,  1.7257,  ...,  0.3333,  0.0503, -0.5512],
        [-1.1939,  0.5658,  0.3760,  ...,  0.9596, -1.5453, -1.5061]])

In [7]:
class_preds = torch.randn(100, 21)

In [8]:
for idx in truth_labels[:, 0]: print(int(idx))

8
8
8
8
8


In [9]:
import torch.nn.functional as F

In [10]:
from src.utilities import compute_giou

bbox_preds = torch.randn(100, 4)

In [11]:
truth_boxes = truth_labels[..., -4:]
truth_boxes.shape

torch.Size([5, 4])

In [12]:
 truth_boxes[0], bbox_preds[0], bbox_preds[1], bbox_preds[2], bbox_preds[3], bbox_preds[4]

(tensor([0.5848, 0.7321, 0.1205, 0.3393]),
 tensor([-0.4935, -0.6907,  0.8392,  1.4709]),
 tensor([ 0.8107,  0.3290, -0.2579,  1.2081]),
 tensor([-1.7520, -0.7380,  0.5295, -1.0440]),
 tensor([-2.5012, -1.1888, -0.2526,  0.2626]),
 tensor([-1.8260, -1.8856, -0.1099, -0.7340]))

In [13]:
from src.utilities import compute_giou

gious = compute_giou(truth_boxes, truth_boxes)

tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])


In [14]:
gious

tensor([[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]])