In [1]:
from pathlib import Path
import sys

sys.path.append(str(Path.cwd().parent))

In [2]:
from src.transforms import test_transforms
from src.dataset import ImageDataset
import torch

annot_path = Path("../data/preprocessed/trainval/annotations.csv")
img_dir = Path("../data/preprocessed/trainval/images")

# test dataset without transforms
dataset = ImageDataset(annot_path, img_dir)
transformed_dataset = ImageDataset(annot_path, img_dir, test_transforms)

In [3]:
_, truth_labels = next(iter(transformed_dataset))
truth_labels.shape, truth_labels

(torch.Size([5, 5]),
 tensor([[8.0000, 0.5848, 0.7321, 0.1205, 0.3393],
         [8.0000, 0.4196, 0.8482, 0.1741, 0.2902],
         [8.0000, 0.0714, 0.8259, 0.1250, 0.3482],
         [8.0000, 0.5357, 0.6562, 0.1071, 0.2812],
         [8.0000, 0.5893, 0.5402, 0.0714, 0.0893]]))

In [4]:
bboxes = truth_labels[:, -4:]
bboxes.shape, bboxes

(torch.Size([5, 4]),
 tensor([[0.5848, 0.7321, 0.1205, 0.3393],
         [0.4196, 0.8482, 0.1741, 0.2902],
         [0.0714, 0.8259, 0.1250, 0.3482],
         [0.5357, 0.6562, 0.1071, 0.2812],
         [0.5893, 0.5402, 0.0714, 0.0893]]))

In [5]:
truth_labels[:, 0]

tensor([8., 8., 8., 8., 8.])

In [6]:
bbox_preds = torch.randn(100, 21)
bbox_preds

tensor([[-0.3897, -0.6947,  1.4539,  ..., -2.5606,  1.4219,  0.8718],
        [ 0.7084,  0.6548,  0.2875,  ...,  0.6055, -0.5384,  0.6616],
        [-2.0326, -0.7326,  1.0360,  ..., -0.2677, -1.3621, -0.1610],
        ...,
        [-1.7324, -0.0763,  0.9585,  ...,  1.2705,  0.6829,  1.5090],
        [-0.3327, -1.3137,  1.3745,  ...,  0.7282,  1.9352,  0.4099],
        [ 0.3256,  1.3101,  0.8482,  ..., -0.3144,  1.7320,  0.7599]])

In [7]:
from src.matching import l1_cost, classification_cost

class_costs = classification_cost(bbox_preds, truth_labels[:, 0]).shape

In [8]:
class_preds = torch.randn(100, 21)

In [9]:
for idx in truth_labels[:, 0]: print(int(idx))

8
8
8
8
8


In [10]:
import torch.nn.functional as F

In [11]:
lst = []
for idx in truth_labels[:, 0]:
    print(int(idx))
    lst.append(-F.softmax(class_preds, dim=-1).select(-1, int(idx)).unsqueeze(-1))

8
8
8
8
8


In [12]:
lst[1]

tensor([[-0.0769],
        [-0.0414],
        [-0.1821],
        [-0.1168],
        [-0.0343],
        [-0.0128],
        [-0.0489],
        [-0.0614],
        [-0.0110],
        [-0.1064],
        [-0.0468],
        [-0.0053],
        [-0.0119],
        [-0.0873],
        [-0.0393],
        [-0.0403],
        [-0.0319],
        [-0.0475],
        [-0.0293],
        [-0.0104],
        [-0.1213],
        [-0.0565],
        [-0.0710],
        [-0.0460],
        [-0.0329],
        [-0.0068],
        [-0.0251],
        [-0.0172],
        [-0.3177],
        [-0.0092],
        [-0.0502],
        [-0.0082],
        [-0.0100],
        [-0.0805],
        [-0.0402],
        [-0.0279],
        [-0.0725],
        [-0.0854],
        [-0.0068],
        [-0.0224],
        [-0.1509],
        [-0.0241],
        [-0.0399],
        [-0.1220],
        [-0.0227],
        [-0.0695],
        [-0.0107],
        [-0.0184],
        [-0.0428],
        [-0.0093],
        [-0.0041],
        [-0.0544],
        [-0.

In [14]:
-F.softmax(class_preds[0], dim=-1)

tensor([-0.0189, -0.0619, -0.0365, -0.0400, -0.0041, -0.0656, -0.0787, -0.1229,
        -0.0769, -0.0173, -0.0064, -0.0237, -0.0185, -0.0916, -0.0885, -0.0235,
        -0.0134, -0.0333, -0.0305, -0.0087, -0.1392])