In [2]:
import torch

a = torch.arange(3)
b = torch.arange(3)

a, a.shape, b, b.shape

(tensor([0, 1, 2]), torch.Size([3]), tensor([0, 1, 2]), torch.Size([3]))

In [3]:
a + b

tensor([0, 2, 4])

In [6]:
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = torch.tensor([10, 20, 30])

a, a.shape, b, b.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]),
 tensor([10, 20, 30]),
 torch.Size([3]))

In [7]:
a + b

tensor([[11, 22, 33],
        [14, 25, 36],
        [17, 28, 39]])

In [10]:
a = torch.zeros(2, 2, 3)

b = torch.tensor([10, 20, 30])

a, a.shape, b, b.shape

(tensor([[[0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.]]]),
 torch.Size([2, 2, 3]),
 tensor([10, 20, 30]),
 torch.Size([3]))

In [11]:
a + b

tensor([[[10., 20., 30.],
         [10., 20., 30.]],

        [[10., 20., 30.],
         [10., 20., 30.]]])

In [17]:
a = torch.randn(5, 4)
b = torch.randn(3, 4)

a.shape, b.shape

(torch.Size([5, 4]), torch.Size([3, 4]))

In [18]:
inter_x1 = torch.max(a[:, None, 0], b[None, :, 0])
inter_y1 = torch.max(a[:, None, 1], b[None, :, 1])
inter_x2 = torch.min(a[:, None, 2], b[None, :, 2])
inter_y2 = torch.min(a[:, None, 3], b[None, :, 3])

inter_x1.shape, inter_y1.shape, inter_x2.shape, inter_y2.shape

(torch.Size([5, 3]),
 torch.Size([5, 3]),
 torch.Size([5, 3]),
 torch.Size([5, 3]))

In [35]:
inter_x1[0], inter_y1[0], inter_x2[0], inter_y2[0]

(tensor([-0.8781, -0.8781,  0.9312]),
 tensor([1.0240, 1.0240, 1.0240]),
 tensor([ 0.2586,  0.2586, -0.9226]),
 tensor([-0.5306, -0.1742, -0.0438]))

In [30]:
intersection_coords = torch.cat((inter_x1[:, :, None], inter_y1[:, :, None], inter_x2[:, :, None], inter_y2[:, :, None]), dim=-1)

In [40]:
intersection_coords.shape, intersection_coords[0]

(torch.Size([5, 3, 4]),
 tensor([[-0.8781,  1.0240,  0.2586, -0.5306],
         [-0.8781,  1.0240,  0.2586, -0.1742],
         [ 0.9312,  1.0240, -0.9226, -0.0438]]))

In [41]:
inter_w = (intersection_coords[..., 2] - intersection_coords[..., 0]).clamp(min=0)
inter_h = (intersection_coords[..., 3] - intersection_coords[..., 1]).clamp(min=0)

inter_w.shape, inter_w[0], inter_h.shape, inter_h[0]

(torch.Size([5, 3]),
 tensor([1.1367, 1.1367, 0.0000]),
 torch.Size([5, 3]),
 tensor([0., 0., 0.]))

In [42]:
inter_w * inter_h

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [45]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([7, 8, 9])

a.shape, b.shape

(torch.Size([2, 3]), torch.Size([3]))

In [46]:
torch.max(a, b)

tensor([[7, 8, 9],
        [7, 8, 9]])